### ISSUE TITLE
(Spring term) Merge WebSocket JOIN_PLAYER and JOIN_OBSERVER into CONNECT_TO_GAME

### ISSUE THREAD

**Issue by ThanGerlek** [softwareconstruction240/softwareconstruction#103]
Ambiguity: HTTP join vs WS join

To do:
- Merge JOIN_PLAYER and JOIN_OBSERVER into one CONNECT_TO_GAME command (remove playerColor field)
- Remove HTTP join as observer
- UI still needs an “observe” command
- Update all tests to match
- Add phase 6 passoff tests requiring authorization for every UserGameCommand (make it clear in the specs this is required)

**Comment by 19mdavenport** [comment]
If you haven't already. I'll get the test cases.

**Comment by 19mdavenport** [comment]
Also, @prattnj suggested that the command just be called CONNECT and we rename the web socket endpoint to be /ws. 

@ThanGerlek what do you think about that?

**Comment by prattnj** [comment]
I've done everything so far except for the tests. Everything in the specs, instructions, and starter code has been updated.

**Comment by frozenfrank** [comment]
This was resolved by #113
