### ISSUE TITLE
GitHub setup assignment requires submitting the chess starter code to autograder

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/softwareconstruction#115]
## Overview
Currently, the GitHub repo instructions just have students create a repo and submit the URL for manual grading. The assignment walks them through making a commit, but the TA's don't dock any points for that. The overall attitude is that the autograder is the source of truth, and if they don't set it up properly, they won't get points in the future. 

Without any validation, students end up running into the repo setup & project clone issues on Phase 0. It may be helpful to do all the starter-code cloning and pushing into GitHub as part of the setup, and we can even have them do an initial commit from inside Intelli-J. Then they can:
1. Submit the URL to Canvas
2. Submit the code on the autograder to receive a score

From the source:
> Having the students extract the chess files to their repo, submitting the URL to canvas, and then running the autograder to check if their code in the repo successfully builds. If the code does successfully builds, then the autograder would give them full points. 
> 
> It would require a bit more work on the students hand, but it should hopefully catch the issue of packaging or build failures in phase0 earlier and remove the need for us to manually grade that assignment.
> — @Fiwafoofa 

## Credit
@Fiwafoofa

**Comment by frozenfrank** [comment]
@jerodw We had meant to bring this up the TA meeting on Monday. Since we didn't, I wrote up an issue and hopefully we'll remember to talk about it next week 📆  

@prattnj What do you think about this idea?

**Comment by Fiwafoofa** [comment]
We finally discussed it. A slight changed was made to only require and verify that the student provided a valid and public github url. Verifying the chess starter code is not required as the assignment is due extremely early in the term/semester, leaving students with not enough time in case they get errors
