### ISSUE TITLE
Consolidate and Elucidate Programming Exam Questions

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/softwareconstruction#146]
## Overview
In the 26 Sept 2024 TA meeting, we discussed the programming exam and decided to make as many adjustments as possible to:
1. Simplify the test taking experience, AND
2. Support linux users

This work improves upon the work brought up by #142. It relates to the work completed in #136.

## Description
I believe this work is already under way.

Specifically, we want to:
- [x] Combine all Programming Exam information into the [programming exam review](https://github.com/softwareconstruction240/softwareconstruction/blob/main/instruction/programming-exam-review/programming-exam-review.md) page
- [ ] Include instructions for Linux users to attempt to take the exam, respecting the following priorities
    - Prefer to find or borrow a Windows/mac device from a friend
    - Then attempt to use a browser spoofer to take the exam
    - Then reach out to a professor if nothing else will work (there are other options)
- [ ] Remove unnecessary pages from the course blueprint now that the content has been moved into the GitHub page

## Assignment
@Truthwatcher64 Has taken the responsibility for writing the Programming Exam with Linux instructions and combining the information into the GitHub page. He would be marked as the "assignee" of this PR, except that he is not available as an option in this `softwareconstruction` repo.

## Authorization
This was authorized by @leesjensen and @jerodw

**Comment by frozenfrank** [comment]
Related notes from a recent TA Meeting:
> **Programming Exam**
> * Remember, no more notes
> * You can use a blank sheet of paper
> * No headphones
> * They can listen to music as long as Examity can hear it
> * Put everything on Github and link to it from Canvas
> * Put Course Policies on Github

**Comment by leesjensen** [comment]
In an attempt to make sure we are all working towards the same target, the following is a presentation of the larger goal. Currently we have:

![image](https://github.com/user-attachments/assets/b991c10d-feb0-4144-b945-4dc34f0a2196)

Here is the plan:

1. Get rid of notes sheet. Remove the instruction and all references to a note sheet
1. Move the **Programming Exam instructions** to a GitHub topic. Include the topic in the course schedule and module list. Reference this topic in all of the remaining Canvas items. Remove the Canvas page for this topic.
1. Combine **Official Programming Exam (Proctored)**, **Official Programming Exam Retake 1 (if needed) (Proctored)**, and **Official Programming Exam Retake 2 (if needed) (Proctored)** into a single Canvas quiz that allows for three retakes.
1. Move the **Examity Troubleshooting Guide (Auto Proctored)** into the **Programming Exam instructions** to a GitHub topic.
1. Carefully review the resulting **Programming Exam instructions** GitHub topic to make it clear, concise,  more encouraging, and less threatening.
1. Question: Is it possible to combine the **PRACTICE Prgoramming Exam** with the **Examity Practice Quiz (Proctored)**?

With all of this done we should have:

1. One topic in GitHub for the programming exam.
1. Two quizes in Canvas (the intro to the quiz references the GitHub topic):
    1. Practice programming exam (proctored)
    1. Programming exam (proctored) - limited to 3 retakes

**Comment by frozenfrank** [comment]
@leesjensen @jerodw
In a TA meeting, there had been a discussion about having the following three items:
1. Practice Programming Exam (unproctored, can be used under professor direction to bypass examity when things go all wrong)
2. Examity Setup Quiz (proctored, verifies the student can use Examity)
3. Programming Exam (Accounts for all three re-takes)

I don't remember what we decided on based on the conversation in class. Does the most recent message indicate that we **will not have** an unproctored "Practice Programming Exam?"

**Comment by jerodw** [comment]
This all looks good to me but I don't believe we can combine the practice programming exam with the examity setup quiz, and I don't think we should even if we can. Currently the practice programming exam can be used if needed to let a student take the exam for credit without proctoring when they have issues that prevent Examity from working for them. Combining them would eliminate this option.
