### ISSUE TITLE
Discuss modifying board requirements for Phase 5

### ISSUE THREAD

**Issue by 19mdavenport** [softwareconstruction240/softwareconstruction#158]
To discuss in a future TA meeting:

The phase 5 specs currently say that the board should be printed from both perspectives every time. We may want to change this to print only the color the player is trying to join as, or potentially we could make it a separate runnable as the code for it in Phase 5 is temporary anyway.

**Comment by ThanGerlek** [comment]
#161 loosens the requirement to allow both options, at least for this semester. Later on we can require something more specific if we want.

**Comment by 19mdavenport** [comment]
Discussed and I believe a resolution was reached: 
- require only one board - from the perspective of the individual player when joining or the team playing white pieces perspective when observing
- not required (but recommended) to loop through and look at pieces on an actual board rather than hardcoding the starting board (what phase 6 actually needs)
- no separate runnable
