### ISSUE TITLE
Allow TAs to Submit PRs from "The Inside"

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/softwareconstruction#165]
## Overview

TAs want to be treated as "part of" the organization and be able to submit PRs from the internal organization rather than needing to leverage personal forks.

## Discussion
As discussed in the TA meeting on Nov 14th, the TAs want to streamline internal operations by creating branches inside the `softwareconstruction` and `chess` repositories. The professors should install branch protections so that they remain kings 👑 over the the `main` branch. Changes will still be proposed via Pull Request, and the professors will remain in full control of the content that actually matters.

This will streamline the process required for TAs to submit PRs and also enable TAs to collaborate and adjust each other's PRs before the professors review them.

## Implementation
~The branch protections will leverage GitHub [code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) to specifically restrict the people who can approve PRs. This is the key feature we want from the Code Owners feature:~

> People with admin or owner permissions can require that pull requests have to be approved by code owners before they can be merged.

~The code owners file could be managed by directly adding professor GitHub handles to the `.CODEOWNERS`~

**UPDATE:** After performing more research, I believe the branch protections with CodeOwners will actually not give us the desired effect. It will be easier to set up and maintain the Rulesets feature instead. These have the key characteristic that they can be viewed by anyone with view access to the repo, meaning they can be discovered better than branch protections which are available to admins only. Additionally, I may be able to prepare an "Import" for the professors to easily set up without a lot of hassle.

Here are a few key details to understand about [GitHub rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets):
> * Anyone with read access to a repository can view the repository's rulesets.
> * You can use rulesets to target branches or tags in a repository or to block pushes to a repository and the repository's entire fork network.
> * Rulesets work alongside any branch protection rules in a repository. [Source.](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets#about-rulesets-and-protected-branches)
> * If the same rule is defined in different ways across the aggregated rulesets, the most restrictive version of the rule applies. [Source.](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets#about-rule-layering)

## Steps To Resolve
For each of the target repositories:
1. Visit the Rulesets settings page ([softwareconstruction](https://github.com/softwareconstruction240/softwareconstruction/settings/rules), [chess](https://github.com/softwareconstruction240/chess/settings/rules))
2. Click "Add new Ruleset" > "Import a ruleset"
3. Provide this preloaded ruleset file (it will allow you to review the settings before applying them)
    * [Professor Kingship 👑.json](https://github.com/user-attachments/files/17817321/Professor.Kingship.json)
4. Review the key settings of this ruleset
    * The enforcement status is set to **Active**
    * **Repository admins** _and_ **Organization admins** bypass the rule
    * This only protects the **default branch** (`main`)
    * It restricts all updates, deletions, and creations
    * _This means that only admins at the repo/org level can merge into the main branch which excludes TAs who only have write access._
5. Deploy the ruleset
6. Test to confirm it works properly
    * A professor should be able to merge a PR into `main`
    * A TA should should NOT be able to merge a PR into `main`

**Comment by leesjensen** [comment]
Done
