### ISSUE TITLE
UML missing method

### ISSUE THREAD

**Issue by 19mdavenport** [softwareconstruction240/softwareconstruction#17]
The UML diagram on the [phase 1 specification page](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/1-chess-game/chess-game.md#code-class-structure) is missing the setTeamTurn() method in the ChessGame interface. Not sure how big of a deal this is, just thought I'd make someone aware

**Comment by leesjensen** [comment]
The method was added to the diagram.
