### ISSUE TITLE
Test that Students actually use BCrypt

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/softwareconstruction#60]
## Discussion
This could be easily accomplished by adding a new required method to the Phase4 starter code that requires them to give us the stored password hash for a given user. While this is not common in the industry, it would give us an avenue to verify that:
1. The stored string is not the exact password
2. That BCrypt can use the returned string to verify the password we originally created for them

Ideally we would be able to directly their database to actually verify that they are NOT storing the password we given them. While this seems reasonable due to the fact that we are supplying the students with a db-properties file, we actually are not and do not want to enforce their database schema. They should be allowed to use any schema they want. This greatly add great complexity to the idea of directly testing their database to the point of pursuing a different route.

## Requirements
Fulfilling this issue would require doing **all** the following:
1. Retrieving the stored password from the students via some method (discussed above)
2. Modifying the Phase 4 test cases to validate a) that the student is _not_ returning the string we originally provide them and b) that the string can be interpreted by BCrypt to validate a known password

**Comment by leesjensen** [comment]
I think this encourages a bad practice of adding production code that is only used to test some internal facet. This leads to leaks in abstraction and potential security violations. We already see this in the horrible `clear` endpoint.

I don't feel like we really want to increase the complexity and coupling in order to test that they are encrypting.
