### ISSUE TITLE
Phase 0 Tests: Gap in testing allows problems to slip that cause trouble in Phase 1

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/softwareconstruction#62]
## Description
In general, we should create the the test cases to be comprehensive enough to enforce all the things that are important to us and required for future phases. 

Consistent with principles of test-driven-development, the test cases should be sturdy enough to feel confident that any code that passes it actually **is** up-to-snuff. A case apparently exists to not require the full rigor of the specifications in the test files; however, that seems to be living short of the definition of good tests, and also as seen below, it ends up hurting the students who only discover the errors later because the tests didn't point out the flaws early (that's the point of tests).

## Source
> **STUDENT:** This is just something I noticed that the test cases for phase 0 dont cover that got be a little caught up on phase 1. If the pawn is at the starting position and there is an enemy to its right or left then it can also move there, the tests only test for if the pawn isnt in starting position it seems

> **TA:** There are a lot of things that get by the test cases. They're not meant to be completely comprehensive, just provide a reasonable standard. If you want to make sure your code lives up to a higher standard, you're more than welcome to write your own test cases for your own code

> **STUDENT:** yeah, i understand. I was just mentioning it in case other people ran into the same problem because I had to refactor my phase 0 code a little bit

## Proposal
Add new test cases that validate the following circumstances:
* Pawn capturing from the starting position
* Pawn movement on the edges of the board (left and right, white and black)
* Pawn capturing from the edges of the board (white and black)
* White pawn on the 6th row that can attack diagonally
* Pawn cannot capture a piece behind it

**Comment by 19mdavenport** [comment]
If we're really that interested in making things as absolutely comprehensive as possible, here's another:

**Comment by frozenfrank** [comment]
@19mdavenport 
> If we're really that interested in making things as absolutely comprehensive as possible...

**Yes!** We do want to gather these ideas. This collaborative conversation is exactly the kind of thing that helps the project get better with more diverse perspective 😄

**Comment by 19mdavenport** [comment]
@frozenfrank 
> **Yes!** We do want to gather these ideas. 
Usually these are decisions we leave up to the professors. Ultimately they're the ones that get to make decisions, TA's just get to propose things.

**Comment by frozenfrank** [comment]
Other TA's have been reporting similar issues. The description has been updated to reflect these additional proposals.

## Reports
> **HEAD TA:** A note for the the phase 0 test cases next semester, the current version of the pawn moves test does not check for a pawn on the edge of the board. I have seen a couple of students today running into issues because they have pawn capture is going out of bounds in phase 1.

> **TA:** Also there should be a test where there is a white pawn on the 6th row that can attack diagonally. We had two people yesterday who failed this particular edge case 🙂

**Comment by leesjensen** [comment]
The test cases were all written by TAs. If you feel that there is a case that is really missing that has a significant impact on the students learning experience then I would suggest a pull request.

However, testing is an art. There is no such thing as a perfect set of tests (at least at a reasonable cost). Everything is a ROI discussion. You are always trading something off. It seems like the bulk of the students didn't have any problem with this. If we introduce a significant number of additional test cases that don't teach anything new, we should wonder what we could have spent our time on that was more meaningful.

**Comment by frozenfrank** [comment]
Thanks for the comment and direction.

I see that you closed this issue. Is that a decision NOT to spend time on
improving these test cases? Alternatively, there is a tradeoff, and it may
still make sense, it could make sense to leave this issue open so that a
future TA may have a chance to prioritize this.

**Comment by frozenfrank** [comment]
As discussed with @leesjensen, I will take this issue to add at least a check for pawn movement near the edge of the board.

Unfortunately, with only `write` access to the repository, I don't have the ability to add this to the TA Project with our Kanban board. This is not a blocking issue to me, but here are three options for moving forward:
1. Do nothing. I can tackle the issue as-is without having it on the Project
2. Someone with permission can add it to the board for me. Once it's on the board, I may or may not have the ability to update it. Could be nice though.
3. Give me [Triage](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#repository-roles-for-organizations) access to the repo. This would give me the ability to manage details like this, while still not allowing me access to push directly to the repository.
