### ISSUE TITLE
Phase 2 Starter Diagram: Generalize RegisterService to Service.

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/softwareconstruction#67]
## Overview
Change the value of the middle layer in the example and in the starter file to just show "Service" instead of "Register Service."

## Discussion
The main point of the diagram is to think through and understand the relationship between the different layers of your server code at a high level. It’s sufficient to think about it merely as “Server,” “Services,” and “DataAccessObjects” where there is one Server, multiple “Services” (ex: RegistrationService and GameService) and multiple “DataAccessObjects” (ex: UserDAO, GameDAO, AuthDAO). However, the over-specifity of the example interferes with this generalization. Additionally, the starter code uses this same title, but the whole column is reused for all of the methods.

**Comment by leesjensen** [comment]
Done.
