### ISSUE TITLE
Improve Navigability of Instruction Pages

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/softwareconstruction#68]
## Current Secnario
Currently, the repo has many folders. Each of the folders has a single markdown file that contains the main content for that folder, and they usually have several other related resources in the folder as well such as images, files, GIF's, and more. Usually, none of the other files are meant to be directly navigated to, but are included as links to the main file.

While this works system works just fine, the system has it's difficulties. Here are two:
1. Navigating between folders in GitHub (the source of the data) requires choosing the folder of interest, and then scanning the available files to locate the `.md` file containing the information.
2. The files are named similarly to the name of the folder. Not only does this introduce a duplication of information into the folder structure (not DRY), but is also means that the file may appear in any random location among the related files. In some folders, the file will appear close to the top of the list, and in other folders it will appear near the bottom of the files in the directory.

This is only an issue for some users. People who only click on links in the page to navigate between pages never notice nor care what the files are named; they also won't care if we rename the files to something else. However, other power users (like us TA's and students searching for information among the `instruction` folders) do navigate between the files directly. 

### Option 1: Publish as GitHub Pages
Publishing the content as a GitHub Pages site may provide easier access to nested files. I'm not entirely sure what the capabilities are here, but I assume that they would be helpful.

### Option 2: Rename files to README.md
This would be one simple change that reduces cognitive load and increases the usability of the system for us. Specifically:
* Inside GitHub, when a folder contains a `README.md` file, the contents of that file are automatically rendered when navigating _only_ to the folder. This simplifies the process for readers because it eliminates the need to find another file inside the folder which actually contains the relevant information.

**Comment by leesjensen** [comment]
The hope that the students are using the [instruction topics](https://github.com/softwareconstruction240/softwareconstruction/blob/main/instruction/modules.md#readme) page or the [schedule page](https://github.com/softwareconstruction240/softwareconstruction/blob/main/schedule/winter2024.md) for their navigation and not walking around in the directory structure.

The solution I would like to move to is to use a wrapper around GitHub that provides navigation. This is how it is done for CS 260 with learn.cs260.click.

Publishing to GitHub Pages wouldn't really help with the navigation unless we put specific links in all the instruction that controlled the navigation.

For me personally I would find it really confusing (as the author) to have every page named README.md. I much prefer the filename to be explicit for the content. I don't really see that as a DRY violation. One is the directory that contains all of the files for the topic. The other is the file that contains the instruction for the topic. It may be a duplicate naming violation, but even that is a stretch.
