### ISSUE TITLE
Spelling Corrector Setup missing txt files

### ISSUE THREAD

**Issue by 19mdavenport** [softwareconstruction240/softwareconstruction#7]
I would fix this myself and submit a pull request, but am having difficulties getting the screenshot to exactly match the other screenshots. 

The spelling corrector [setup instructions](https://github.com/softwareconstruction240/softwareconstruction/blob/main/spelling-corrector/setup/setup.md) don't include instructions for putting the `.txt` files in the project, and a few students have come in having problems with not including the files

Screenshot missing files: [here](https://github.com/softwareconstruction240/softwareconstruction/blob/main/spelling-corrector/setup/starter-code.png)

**Comment by leesjensen** [comment]
Thanks for submitting this. All fixed.
